### PR TITLE
Servlet API downgrade, correction in groupId and made some service references optional

### PR DESCRIPTION
**Pull request by sergehuber**
Hello,

This pull request contains a few changes I made to be able to use this project in our of our products. 
- Quick correction in the build.gradle file where the groupId in MyPublication was still the old one
- Downgraded the Servlet API version from 3.1.0 to 3.0.1 because our application platform only support 3.0 for the time being and I couldn't identify a strong need to use version 3.1 in the servlet (unless I missed something ?)
- Made the service references for the context and execution strategy providers optional as they do have default implementations.

I hope these changes will be useful and may be accepted back into the project. If not please don't hesitate to comment on this PR I will do my best to address any issues or questions.

Best regards,
  Serge Huber.

### CODE REVIEW

**Comment by yrashk** [comment]
Hi Serge,

I follow https://rfc.unprotocols.org/spec:1/C4/ protocol so all PRs are proactively merged :)

**Comment by yrashk** [comment]
I merged the request, however I want to figure out the best way to go about servlet version. The reason why the project had 3.1.0 is that in my work, I use Karaf (4.0.7 at the moment) which, through its `war` feature, stipulates 3.1.0 and carrying two servlet libraries is problematic. I recently had a related problem https://dev.vaadin.com/ticket/20190

What application platform do you use?

**Comment by yrashk** [comment]
P.S. Thank you for the contribution!

**Comment by sergehuber** [comment]
Hello Yurii,

Our platform is our own web application (Jahia DX), that needs to run on servers such as IBM WebSphere and some of the old versions are always lagging behind in terms of Servlet API support.

However it should be possible to specify a version range for the Servlet API dependency so that we can say that we can to support >= 3.0 < 3.2. I'm not sure how to do this with Gradle (I use Maven) but I'll see if I can give it a try.

cheers,
  Serge...

**Comment by sergehuber** [comment]
Actually I just checked the generated JAR headers and it should work because in the MANIFEST.MF we have the following values : 

	javax.servlet;version="[3.0,4)",
	javax.servlet.http;version="[3.0,4)",

So if you provide a Servlet API 3.1 bundle it should work. However if you set the dependency to 3.1 it will generate ranges that are [3.1,4) which will make it impossible to use on platforms that use Servlet API 3.0 (as is our case)

**Comment by yrashk** [comment]
Serge, 

Thanks again! I've uploaded 0.6.4 to Maven Central, might take a few hours to sync.

Yurii.

**Comment by sergehuber** [comment]
Thanks that's great news I'll test it as soon as its available !

**Comment by sergehuber** [comment]
Ok I've tested it works fine from here. Thanks for accepting this request quickly.

**Comment by yrashk** [comment]
No worries, and thank you for the contribution!

**Pull request merged**
