### PR TITLE
Add support for operationName that was not implemented

### PR DESCRIPTION
**Pull request by sergehuber**
Add support for operationName that was not implemented. We can now build GraphQL code such as : 
```
query UserQuery {
  dx {
    user(userKey: "root") {
      id
      properties {
        key
        value
      }
    }
  }
}

mutation CreateNode {
  createNodeByPath(name:"test", parentPath: "/") {
    identifier
    path
    parentIdentifier
  }
}
```
And choose which operation to execute using GraphiQL's play button.

### CODE REVIEW

**Comment by yrashk** [comment]
Thank you!

**Comment by sergehuber** [comment]
You're welcome, that's all I have for now. I'll be demoing this code this afternoon so feel free to release it :)

**Comment by yrashk** [comment]
Just pushed out 0.7.0!

**Comment by sergehuber** [comment]
Very cool thanks a lot !

**Pull request merged**
