### PR TITLE
Upgrade graphql-java to 2.3.0

### LINKED ISSUE #12: Bump graphql-java version if possible
Per @jplock at https://github.com/graphql-java/graphql-java/issues/268#issuecomment-270201325. Thanks

### PR DESCRIPTION
**Pull request by jplock**
Fixes #12

### CODE REVIEW

**Comment by jplock** [comment]
doh!  looks like there are tests to fix or something.

**Comment by jplock** [comment]
I don't know how to fix these errors:

```
Gradle suite > Gradle test > graphql.servlet.GraphQLVariablesTest.nonNullvariableTyping FAILED
    java.lang.ClassCastException at GraphQLVariablesTest.java:89
Gradle suite > Gradle test > graphql.servlet.GraphQLVariablesTest.variableTyping FAILED
    java.lang.ClassCastException at GraphQLVariablesTest.java:69
```

@yrashk any ideas?

**Comment by dminkovsky** [comment]
Hey, I reached out to the other maintainers.

In the meantime, when you say you don't know how to fix these errors, what do you mean? I'm not familiar with the project (not using the servlet API for GraphQL at this time), so I'm not sure exactly what the tests are doing. Look at [the code](https://github.com/graphql-java/graphql-java-servlet/blob/4aae2599e8667f762fcfd693e15b15a0320e4315/src/test/java/graphql/servlet/GraphQLVariablesTest.java) it looks like both failures occur at `servlet.bindQueryProvider(queryProvider);`. Any ideas what that line does?

**Comment by yrashk** [comment]
Guys, the project is not really abandoned — I am just being busy these
days, hence dropping the ball on issues. I will be able to devote a bit
more time in this coming month, but likely after Feb 15.

Sorry about that!

**Comment by dminkovsky** [comment]
We'll figure it out together as time permits! :)


пт, 3 февр. 2017 г. в 10:36, Yurii Rashkovskii <notifications@github.com>:

**Comment by jplock** [comment]
Sorry @dminkovsky I should have been more clear.  The test suite for this project doesn't do a whole lot and it looks like the test failures are coming somewhere within graphql-java itself (those `java.lang.ClassCastException` exceptions).  That's why I'm not sure how best to fix it.

I appreciate everyone's help with this.

**Comment by apottere** [comment]
@yrashk Any chance you could come back to the project soon?  I'm happy to help maintain it if you can't.

Otherwise I might end up maintaining a fork - I love what you've done here, but a few people (myself included) need it to move forward.

**Comment by yrashk** [comment]
@apottere, I am happy to delegate maintenance — I completely lack time to maintain this library right now.

**Comment by apottere** [comment]
@yrashk awesome, let me know how you want to proceed.

**Comment by yrashk** [comment]
@apottere I sent a request to @andimarek to add you as a project maintainer/admin. I will also need you to sign up for Maven Central releases functionality at https://issues.sonatype.org

**Comment by apottere** [comment]
I'm `ddcapotter` on https://issues.sonatype.org

**Comment by apottere** [comment]
@jplock The test errors were because the object in the tests used the same java class for input and output, causing graphql-java-annotations to create two different types (input and object) with the same name.  When the schema tried to look up the type from the dictionary, it got the wrong one and couldn't cast it to the correct type.

**Pull request closed without merging**
