### PR TITLE
Added support for instrumentation

### PR DESCRIPTION
**Pull request by ronald-d-rogers**
This is a quick and dirty to add extensibility for instrumentation.
Not sure if this is all that needs to be done.
All tests still seem to pass.

### CODE REVIEW

**Comment by apottere** [comment]
LGTM, thanks!

**Comment by ronald-d-rogers** [comment]
@apottere I know this is closed but I'm not sure where else to ask it. Do you know when the next version containing this will be released? We're trying to decide whether or not to just add our fork into maven as a dependency in some weird way or just wait for the next version. Thanks!

**Comment by apottere** [comment]
I can cut a release tomorrow

**Comment by ronald-d-rogers** [comment]
Cool, thanks alot!

**Comment by apottere** [comment]
@ronald-d-rogers `3.0.1` is released.

**Comment by ronald-d-rogers** [comment]
Great, thanks again for the quick response.

**Pull request merged**
