### PR TITLE
Fix request multipart parsing issue when request is not multipart

### PR DESCRIPTION
**Pull request by nrouge**

### CODE REVIEW

**Comment by ashu-walmart** [comment]
Thanks for the quick turnaround.

**Comment by ashu-walmart** [comment]
@apottere @andimarek @bbakerman, Is it possible to get this merged? Master is broken without it.

**Comment by ashu-walmart** [comment]
@oliemansm Is this PR needed anymore after the changes made for https://github.com/graphql-java/graphql-java-servlet/issues/76 ?

**Comment by oliemansm** [comment]
@ashu-walmart Sorry, I totally overlooked your PR! But this PR is indeed not needed anymore. Already fixed on master now.

**Pull request closed without merging**
