### PR TITLE
Added some documentation for OSGi & Fix another OSGi deployment issue

### PR DESCRIPTION
**Pull request by sergehuber**
Hello, 

In this PR I added some documentation for the OSGi providers, as well as an example on how to use an Apache Karaf feature to package all the dependencies for the graphql-java-servlet project, making it (hopefully) easier to get started. 

There is also a fix to make it more compatible with other OSGi containers, and also switched to OSGi R6 servlet registration patterns.

Let me know if you need any changes.
Best regards,
  Serge...

### CODE REVIEW

**Comment by apottere** [comment]
I like the idea, but it might be better to put it in an `examples/apache-karaf` directory instead of putting the file contents directly in the README.  You could then link from the documentation in the readme to the files in the examples directory.

**Comment by sergehuber** [comment]
Ok should we create this examples directory then ? 

The problem is that the plugin I need only works with Maven, so I'm not sure how to do this.

**Comment by apottere** [comment]
I just created it: https://github.com/graphql-java/graphql-java-servlet/commit/fb1a37eca3c6f38400d3838bc95a5290beef51e9

You can add a subdirectory for your sample and make it as robust as you think it should be - you can make it a maven project and it won't affect the servlet project.

**Comment by sergehuber** [comment]
Ok I've completed all the examples I wanted to provide and updated the README accordingly. I also added a fix for the servlet registration in some (older) OSGi containers. 

The new examples contain a fully running Apache Karaf server package (no binaries, this is generated using a Maven Plugin), that will let users have everything in a single package to get up and running experimenting with GraphQL & OSGi. I've also provided a simple ExampleGraphQLProvider that help see a concrete example.

Let me know what you think !

**Comment by apottere** [comment]
Wow, this is awesome.  Good job!

**Pull request merged**
